experimenter: Avery
prep_choices: [Left optic lobe, Right optic lobe, Whole brain, Optic glomeruli]
driver_choices: [646.AstA-LexA, Mi1-Gal4, 578.AstA-R1-Gal4]
indicator_choices: [GCaMP6f, Syt1GCaMP6f, csChrimson::TdTomato ]

rig_config:

  Bruker_TwoScreens:
    data_directory: E:/Avery
    screen_center: [0, -30]
    rig: Bruker

  Laptop:
    data_directory: /path/to/data
    screen_center: [0, 0]
    rig: (testing)
