experimenter: Emma
prep_choices: [L1]
driver_choices: [L1split-Gal4]
indicator_choices: [jrGECO1a, iATPSnFR ]

rig_config:

  Bruker_TwoScreens:
    data_directory: F:/Emma
    screen_center: [0, -30]
    rig: Bruker

  24HrFitness:
    data_directory: /home/clandinin/minseung/ballrig_data/FlystimData
    screen_center: [0, 0]
    rig: 24HrFitness

  Laptop:
    data_directory: /path/to/data
    screen_center: [0, 0]
    rig: (testing)
