experimenter: izs
prep_choices: [Behavior, Optic lobe, Whole brain]
driver_choices: [L2, nSyb-Gal4]
indicator_choices: [TdTomato, GCaMP7f, GCaMP6f]

rig_config:
  24HrFitness:
    data_directory: /home/clandinin/ilana/VPdata
    screen_center: [0, 0]
    rig: 24HrFitness
    server_data_directory: /home/clandinin/ilana/VPdata/fictrac
    locomotion: True

  40HrFitness:
    data_directory: /home/clandinin/ilana/VPdata
    screen_center: [0, 0]
    rig: 40HrFitness
    server_data_directory: /home/clandinin/ilana/VPdata/fictrac
    locomotion: True

  Bruker_LeftScreen:
    data_directory: E:/path/to/FlystimData
    screen_center: [0,-30]
    rig: Bruker

  Bruker_TwoScreens:
    data_directory: E:/Ilana/StimpackData
    screen_center: [0, -30] #center of two screens and a little down
    rig: Bruker
    server_data_directory: /home/clandinin/data/ilana/StimpackData/fictrac
    locomotion: True

  Laptop:
    data_directory: E:/path/to/FlystimData
    screen_center: [0, 0]
    rig: (testing)
