experimenter: TAC
prep_choices: [Medulla]
driver_choices: [nsyb-SSx, nsyb-SIx, nsyb-SI2, VGAT-SIx, VGAT-IIx, VGlut-SIx, VGlut-IIx, ChAT-SSx, ChAT-SIx, ap-SIx, ap-IIx, Dll-SIx, Dll-IIx, ey-SIx, ey-IIx, Tm3-IIx, Tm3-Ix]
indicator_choices: [GCaMP8m, GCaMP8m-P2A-tdTomato, GCaMP6f, TdTomato]
effector_choices: [Trpgamma1-het, Trpgamma1-homo]

rig_config:

  Bruker_TwoScreens:
    data_directory: E:/Tim/FlystimData
    screen_center: [-50, -30]
    rig: Bruker

  Bruker_TwoColor:
    data_directory: E:/Tim/FlystimData
    screen_center: [-50, -30]
    rig: Bruker