experimenter: TAC
prep_choices: [Medulla]
driver_choices: [nsyb-SIx, nsyb-SI2, nsyb-SSx, VGAT-SIx, GAD1-SIx, VGlut-SIx, ChAT-SIx, ple-SIx]
indicator_choices: [GCaMP8m, GCaMP8m-P2A-tdTomato, GCaMP6f, TdTomato]

rig_config:

  Bruker_TwoScreens:
    data_directory: E:/Tim/FlystimData
    screen_center: [-50, -30]
    rig: Bruker

  Bruker_TwoColor:
    data_directory: E:/Tim/FlystimData
    screen_center: [-50, -30]
    rig: Bruker