experimenter: TAC
prep_choices: [Medulla]
driver_choices: [nsyb-SSx, nsyb-SIx, nsyb-SI2, VGAT-SIx, VGAT-IIx, GAD1-SIx, GAD1-IIx, VGlut-SIx, VGlut-IIx, ChAT-SSx, ChAT-SIx, ple-SIx, ple-IIx]
indicator_choices: [GCaMP8m, GCaMP8m-P2A-tdTomato, GCaMP6f, TdTomato]

rig_config:

  Bruker_TwoScreens:
    data_directory: E:/Tim/FlystimData
    screen_center: [-50, -30]
    rig: Bruker

  Bruker_TwoColor:
    data_directory: E:/Tim/FlystimData
    screen_center: [-50, -30]
    rig: Bruker