experimenter: TAC
prep_choices: [Medulla]
driver_choices: [nsyb]
indicator_choices: [GCaMP6f, TdTomato]

rig_config:

  Bruker_TwoScreens:
    data_directory: E:/Tim/FlystimData
    screen_center: [50, -30]
    rig: Bruker

  Bruker_TwoColor:
    data_directory: E:/Tim/FlystimData
    screen_center: [50, -30]
    rig: Bruker